server:
    port: 21110

eureka:
  client:
    service-url:
      defaultZone: http://192.168.0.250:8888/eureka/


spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: MeetingHuiwuCenter
  datasource:
    url: jdbc:mysql://192.168.0.224:3306/s_meet?serverTimezone=GMT%2B8&characterEncoding=UTF-8&createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver



  jpa:
    properties:
      hibernate:
        dialect: com.hz.general.config.MySQL5DialectUtf8
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
  redis:
    host: localhost
    port: 6379
    password:
    timeout: 2000
